# Generated by Django 4.2.5 on 2023-09-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPost17', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
                ('costo', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='portafolio',
            name='agencia',
            field=models.CharField(max_length=40),
        ),
    ]
