# Generated by Django 4.2.5 on 2023-09-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPost17', '0002_servicios_alter_portafolio_agencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactanos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.IntegerField()),
                ('mensaje', models.CharField(max_length=1000)),
            ],
        ),
    ]
